# Generated by Django 3.1.4 on 2021-01-02 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.IntegerField()),
                ('auction_key', models.IntegerField(unique=True)),
                ('status', models.IntegerField(choices=[(1, 'ongoing'), (2, 'completed')])),
                ('max_bid', models.IntegerField(max_length=5)),
                ('max_bid_customer', models.IntegerField()),
                ('crop_type', models.IntegerField(choices=[(1, 'fruits'), (2, 'vegetables'), (3, 'crops')])),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.IntegerField(unique=True)),
                ('user_name', models.CharField(max_length=120)),
                ('user_type', models.IntegerField(choices=[(1, 'farmer'), (2, 'retailer')])),
                ('address', models.CharField(max_length=500)),
                ('crop_type', models.IntegerField(choices=[(1, 'fruits'), (2, 'vegetables'), (3, 'crops')])),
                ('contact', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Farmer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.IntegerField()),
                ('auctions_created', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Retailer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_key', models.IntegerField()),
                ('auctions_participated', models.CharField(max_length=120)),
            ],
        ),
    ]
